### ISSUE TITLE
Why has there to be a {path*} value in the cookie?

### ISSUE THREAD

**Issue by martinheidegger** [hapijs/makemehapi#102]
The current cookie lesson asks for the solution to present a `{path*}` scope. Why? I can't find a reason on this in the `problem.md`?

[Here] (https://github.com/hapijs/makemehapi/blob/7da6437aadba0dfe2636dbb881302de0621c5a31/exercises/cookies/solution/solution.js#L16) is the solution reference?!

**Comment by lloydbenson** [comment]
@martinheidegger I am not sure what your proposal here is to solve your issue.  Maybe a PR would help.  I am not sure how to proceed with this issue.

**Comment by lloydbenson** [comment]
Haven't heard back on this one, so closing it up.  If you have a suggestion on making things more clear, getting rid of a confusing solution, etc, please re-open or better yet open up a PR so its more clear.

**Comment by martinheidegger** [comment]
@lloydbenson sorry for not coming back at you (too many github issues). Let me clearly state my problem:

[The solution for cookies](https://github.com/hapijs/makemehapi/blob/7da6437aadba0dfe2636dbb881302de0621c5a31/exercises/cookies/solution/solution.js#L16) specifies a `/{path*}` definition which will be rendered as is in the http response. The cookie that is sent to the browser contains "/{path*}" and not the actual path `/`. The solution of the user is compared to the default solution. This means the user has to write exactly "/{path*}" somewhere. Nowhere in [the problem description](https://github.com/hapijs/makemehapi/blob/7da6437aadba0dfe2636dbb881302de0621c5a31/exercises/cookies/problem.md) is a reference to this! 

I am not sure if I am understanding the use of hapi wrong but I just don't get why to add this path specification in the first place?! Isn't `/` enough?

**Comment by lloydbenson** [comment]
Thanks for the feedback!  I will assign this to Ben for now to work on clarifying the instructions.

**Comment by nvcexploder** [comment]
@martinheidegger, there really isn't. You're more than welcome to submit a PR for it, though! :smile:

**Comment by martinheidegger** [comment]
@nvcexploder I would love to but I still fail to understand :cry: : Is it a problem of me not understanding hapi (What does `{path*}` do? Why is it there?) or is it makemehapi being wrong?

**Comment by dylancwood** [comment]
I think that @nvcexploder is saying that there is no reason to use the `'/{path*}'` as the path for the cookie, and that it is fine to change the path to `'/'` in the solution. Let me know if that's right.

**Comment by nvcexploder** [comment]
Yarp.

**Comment by dylancwood** [comment]
@martinheidegger, I will create a PR for this. Just letting you know so that we don't duplicate our efforts.

**Comment by fiveisprime** [comment]
Fixed in makemehapi@2.0.0
