### ISSUE TITLE
Add preferGlobal property to NPM to indicate CLI nature of this module

### ISSUE THREAD

**Issue by peterblazejewicz** [hapijs/makemehapi#108]
The NPM supports `preferGlobal` key to support user experience with modules that are supposed to be installed globally - for example with CLI tools:
http://browsenpm.org/package.json#preferGlobal
https://github.com/rvagg/learnyounode/blob/master/package.json#L38
Add this to package.json will be also reflected in NPM badge:
https://github.com/rvagg/nodei.co/blob/94656f4fbc3e6223a9c7e7f4ed4be5aa67ce1781/lib/draw-npm-badge.js#L166

I could do PR if accepted.
Thanks!

**Comment by peterblazejewicz** [comment]
@lloydbenson Of course not - after a quick review. NPM itself does on the other hand.

**Comment by lloydbenson** [comment]
Yeah I don't think we want to do anything different than other workshoppers
to be consistent.  Also I personally prefer not doing them global even if
its slightly less convenient.  I am not the maintainer of this module
though if you have strong feelings about it.  I'd be happy to assign this
task if you want, but I'd vote to not have it.

**Comment by khalifenizar** [comment]
From the [npm package.json docs](https://docs.npmjs.com/files/package.json#preferglobal):

> preferGlobal
>
> If your package is primarily a command-line application that should be installed globally, then set this value to true to provide a warning if it is installed locally.

Even though I share @lloydbenson's preference to not install workshoppers globally, I don't really think it can be argued that they aren't primarily CLI applications that are mostly installed globally. That indicates to me that the most accurate value for the `preferGlobal` key is `true`.

Given that at least `learnyounode` is already breaking with the consistency, shouldn't we go with the `preferGlobal` value that is most appropriate for workshoppers and have the community enforce consistency with pull requests?

**Comment by lloydbenson** [comment]
I am fine adding this, but I'd like there to be PRs on all workshoppers to ensure workshoppers are consistently done and its not makemehapi specific.  Feel free to open a PR and once there is general consensus within the community we can merge it.  @peterblazejewicz are you submitting similiar PRs to all the workshoppers?

**Comment by peterblazejewicz** [comment]
@lloydbenson 
> are you submitting similiar PRs to all the workshoppers?

OK. Let me do this. Thanks!
