### ISSUE TITLE
Misleading hints in exercise 12 "cookies" - createServer and cookies object

### ISSUE THREAD

**Issue by biozz** [hapijs/makemehapi#111]
In the hints of exercise 12 "cookies" there is a mention of  `createServer` (this is somewhat linked to #103) and `options` object has `cookies` key - both are not used in the current Hapi API. 

> **createServer** takes an options object as a **third parameter**. Using this options object, we can configure the server to handle cookies in various way,
```javascript
>    var options = {
>      state: {
>        cookies: {
>          parse: true ,
>          failAction: 'log'
>        }
>      }
>    };
```

I cannot quite understand what should be the correct sentance there, but I know that these options can be passed to a `route` as a `config`, like this (correct me if I'm wrong): 
```javascript
    config: {
        state: {
            parse: true,
            failAction: 'log'
        }
    }
````

**Comment by lloydbenson** [comment]
You are absolutely right.  I found a few other things too while I was add it.  Let me know if this meets your needs and I can get it merged.  Thanks for letting us know and participating!

**Comment by biozz** [comment]
The change looks good, you can merge it.
