### ISSUE TITLE
404 error on the handling exercise 

### ISSUE THREAD

**Issue by roelof1967** [hapijs/makemehapi#113]
Hello, 

Im now trying to make the handling exercise 

I have this : 

    var Hapi = require('hapi');
    
    var server = new Hapi.Server(); 
    
    server.connection({
     host: 'localhost',
     port: Number(process.argv[2] || 8080)
     });
    
    server.route({
     method: 'GET',
     path: '/',
     handler: {
       file: 'index.html'
      }
    });
    
    server.start();

but as soon as I do makemehapi run I see a 404 error 

Roelof

**Comment by arb** [comment]
Do you have an "index.html" file at the route of the project?

**Comment by roelof1967** [comment]
No, I thought that that file was provided by the lessons

**Comment by lloydbenson** [comment]
Do you think https://github.com/hapijs/makemehapi/blob/master/exercises/handling/problem.md needs more clarity?  If so feel free to PR will suggestions.

**Comment by roelof1967** [comment]
I will think about what can be improved.

**Comment by lloydbenson** [comment]
Closing this as it is resolved.  Feel free to open a PR if you have a suggestion on making the instructions more clear.
