### ISSUE TITLE
directories forbidden error 

### ISSUE THREAD

**Issue by roelof1967** [hapijs/makemehapi#115]
i have this : 

    var Hapi = require('hapi');
    var Path = require('path')
    
    var server = new Hapi.Server();
   
    server.connection({
        host: 'localhost',
        port: Number(process.argv[2] || 8080)
    });
    
    server.route({
        method: 'GET',
        path: '/{param*}',
        handler: {
            directory: {
                path: Path.join(__dirname + '/public')
            }
        }
    });

    server.start();

but when I run it I see this error : 

{"statusCode":403,"error":"Forbidden"}

I have made that directory as a normal user 

Roelof

**Comment by lloydbenson** [comment]
I dont have quite enough to go on here.  What files do you have underneath public and what endpoint are you calling?  I suspect you may be doing the same thing as in your other error where you are not populating files.

**Comment by roelof1967** [comment]
I have the file files.html under public. Can it be a help to put this exercise on github so you can look at it.

**Comment by lloydbenson** [comment]
So you are doing /files.html in your url and thats where you are getting
the 403?  If so please provide dir structure and permissions.  I am also
assuming you are starting it up as the same user that you made it.

**Comment by roelof1967** [comment]
no, 

I made the above script and after that im doing makemehapi run directories.js. 
I do everything as a normal user but I can made a ls -al of the makemehapi directory. 

Roelof

**Comment by lloydbenson** [comment]
Ok, looks like the file here is called file.html.  So if you do a node directories.js (assuming directories.js is the file you have your code, and then you go to your browser and do /file.html it gives you a 403?

**Comment by roelof1967** [comment]
I have not tried. 

I see the 403 error after doing makemehapi run directories.js like I said a few times before.

**Comment by lloydbenson** [comment]
Ah.  I thought you had already finished the exercise.  The problem indicates:

Create a server which routes requests to the path `/foo/bar/baz/file.html` ....

Your solution does not do that.  Your solution is / not /foo/bar/baz.  So it properly is trying the problem route, and it indeed does not exist so the error is completely valid.

**Comment by roelof1967** [comment]
Thanks, problem solved.

As far as I see there is no difference in this exercise and the file exercise. Both serve a page on a particular page. 

I think this exercise can also be done by this : 

~~~

server.route({
    method: 'GET',
    path: '/far/boo/baz',
    handler: {
        file:  ( public/file.html')
        }
    }
});

~~~

Do I understand it right or not ? 

Roelof

**Comment by roelof1967** [comment]
On the next exercise again a 404 error on makemehapi run views.js who looks like this : 

    var Hapi = require('hapi');
    var Path = require('path');
    
    var server = new Hapi.Server();
    
    server.connection({
        host: 'localhost',
        port: Number(process.argv[2] || 8080)
    });

    server.route({
        method: 'GET',
        path: '/{user}',
        handler: {
            view: "index.html"
        }
    });
    
    server.views({
        engines: {
            html: require('handlebars')
        },
        path: Path.join(__dirname, 'templates')
    });

server.start();

**Comment by lloydbenson** [comment]
Your solution of:

server.route({
    method: 'GET',
    path: '/far/boo/baz',
    handler: {
        file:  ( public/file.html')
        }
    }
});

Does the same thing for a single file but 2 things are pretty different.

1.  The path is specific (not parameterized)
2.  The point of directories is to include multiple files so this solution isn't solving the original problem.

**Comment by lloydbenson** [comment]
Please open up a new issue if you think there is an issue with another exercise.
