### ISSUE TITLE
the "streams" exercise will fail if the user follows the input format to the letter

### ISSUE THREAD

**Issue by Pomax** [hapijs/makemehapi#127]
An input file with content
```
The Pursuit of Hapi-ness
```
will cause the exercise evaluation to fail, as it's also testing for a final newline, which isn't indicated in the assignment. Changing the input to 
```
The Pursuit of Hapi-ness

```
makes the test pass, but doesn't make the most sense from an assignment-doing-person's point of view. That newline was not in the assignment text.

**Comment by fiveisprime** [comment]
This is also closed with #157
