### ISSUE TITLE
the "validation using joi object" assignment needs more hints

### ISSUE THREAD

**Issue by Pomax** [hapijs/makemehapi#131]
Going from "the Joi validation isn't tested" in the "Validation" assignment to "good luck figuring out how to make Joi do the thing we're asking you" in the "Validation using Joi object" assignment is too big a leap.

Pointing to the docs does not help in this case, but is simply throwing the manual at the learner and expecting them to know what they're even looking for. It would be more helpful, and a better learning experience, if the hints give examples of how to do the things the assignment asks for, like how to require one value if another value is some specific value, or missing, and how to make validation pass, or fail, if more than the necessary arguments are found.

Right now, there is a blob of Joi validation that has zero meaning for the learner, without any text that explains why things like `.options()`, `.with()`, and `.without()` are shown, or what they do.

I can't find out how to do the first thing that's being asked, for instance. I've never used Joi before, and despite being proficient in Node, Express, model validation, etc. the Joi package is not presented as very joyful in these two assignments. Instead it's presented as a bloody hard thing that requires I read an entire manual to even understand. Which, even when I read it, doesn't seem to tell me how to do what the assignment makes feel is a rather basic thing.

That doesn't make me hapi =)

**Comment by nvcexploder** [comment]
Checking this out in conjunction with #132

**Comment by nvcexploder** [comment]
@Pomax check this out: https://github.com/nvcexploder/makemehapi/blob/joi/exercises/validation_using_joi_object/problem.md

Does that look like it's on the right path so far?

**Comment by Pomax** [comment]
that's definitely the right path, yes!

**Comment by nvcexploder** [comment]
Cool! I'll continue on it then. :)
