### ISSUE TITLE
Helping exercise #7 Doesnt Render in browser/ Solution code does not pass

### ISSUE THREAD

**Issue by kaona** [hapijs/makemehapi#172]
The solution code for exercise 7 doesnt pass even if you copy and paste it into your editor.

More importantly, the templates are not rending in chrome or firefox.

**Comment by fiveisprime** [comment]
Can you share your solution? The template renders correctly in all browsers for me. :(

**Comment by kaona** [comment]
The solutions is literally cut and pasted from the solution repository....except for the helpers.html which should be helper.html. I apologize for taking your time on that.
