### ISSUE TITLE
Exercise 3 'Handling'

### ISSUE THREAD

**Issue by Euklidian-Space** [hapijs/makemehapi#175]
When I run verify for this exercise the tests fail, but the Actual and Expected seem to be the same. Here is the output.

1.  ACTUAL:    "<html>"
1.  EXPECTED:  "<html>"

2.  ACTUAL:    "  <head><title>Hello Handling</title></head>"
2.  EXPECTED:  "    <head><title>Hello Handling</title></head>"

3.  ACTUAL:    "  <body>"
3.  EXPECTED:  "    <body>"

4.  ACTUAL:    "    Hello Handling"
4.  EXPECTED:  "        Hello Handling"

5.  ACTUAL:    "  </body>"
5.  EXPECTED:  "    </body>"

6.  ACTUAL:    "</html>"
6.  EXPECTED:  "</html>"

7.  ACTUAL:    ""
7.  EXPECTED:  ""

8.  ACTUAL:    ""
8.  EXPECTED:  ""

────────────────────────────────────────────────────────────────────────────────

✗ Submission results did not match expected!

# FAIL

Your solution to HANDLING didn't pass. Try again!

It seems if your text editor does not have tab set to 4 spaces the tests will fail

**Comment by fiveisprime** [comment]
This has to do with newline at the end of the solution file. Adding a newline to the end of your html file will correct the issue.

I update the solution to ignore the newline.

**Comment by fiveisprime** [comment]
Fixed in makemehapi@5.0.1 :+1:
