### ISSUE TITLE
Add `.gitattributes` file

### ISSUE THREAD

**Issue by akihito-takeuchi** [hapijs/makemehapi#188]
When I run the command 'makemehapi', following error message was shown.

env: node\r: No such file or directory

Looks like the line ending of 'makemehapi.js' is DOS. Is that possible to change the line ending to Linux one?

**Comment by alanbhamilton** [comment]
[This article](https://help.github.com/articles/dealing-with-line-endings/#platform-all) from Github Help gives more information on this problem.

Perhaps adding a .gitattributes file to this repo?

**Comment by fiveisprime** [comment]
I'll add the `.gitattributes`

I can't reproduce this though - I'm on macOS 10.12.1 with: `node@7.2.1`, `npm@3.10.10`, `makemehapi@5.2.1`

Everything is working correctly.

**Comment by fiveisprime** [comment]
Okay, never mind, 5.1.0 and 5.2.0 are borked - latest/5.2.1 is okay so I guess the last set of changes fixed the issue. I'll still get `.gitattributes` added though.

**Comment by iwasrobbed** [comment]
I'm getting this today even with the `.gitattributes` file in `5.2.1` and I don't see any file changes when following the [Github instructions ](https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings)
