### ISSUE TITLE
"No such file or directory"

### ISSUE THREAD

**Issue by ankurpatel4888** [hapijs/makemehapi#192]
Have installed nodejs (6.9.2 LTS), hapi globally(version 16.0.1) and have used  "npm install -g makemehapi" (version 5.2.1) using administrative rights on Ubuntu 16.04 but whenever I'm running command "makemehapi" it throws an error of "/usr/bin/env: ‘node\r’: No such file or directory" what is missing? I do want to learn hapi due to my job nature and demand ASAP do you have any solution?

**Comment by fiveisprime** [comment]
This is related to the line ending issue from #188 For a quick fix until I figure out how to get the EOL issue fixed, install an earlier version - `npm i -g makemehapi@5.0.1`

**Comment by probil** [comment]
The problem is `makemehapi.js` has DOS/Windows newline (`\r\n`) but it should be Unix style is ( `\n` ). I will create PR soon

**Comment by probil** [comment]
Hmm... it's already fixed. Maybe the problem is on `npm publish` level

**Comment by fiveisprime** [comment]
Just published `5.2.2`.. from a Mac. Installed and confirmed that `makemehapi.js` and all other files are `LF`.

**Comment by probil** [comment]
No more issue in `5.2.2`. Confirmed on ArchLinux
