### ISSUE TITLE
Solution for Validation fails -- Joi returning message pair in json.

### ISSUE THREAD

**Issue by ingusmat** [hapijs/makemehapi#194]
The solution provided for lesson 9 fails using current versions of Hapi and Joi.  When you correctly complete the assignment (or copy/paste from solutions), you get:

`1.  ACTUAL:    "{\"statusCode\":404,\"error\":\"Not Found\",\"message\":\"Not Found\"}"`
`1.  EXPECTED:  "{\"statusCode\":404,\"error\":\"Not Found\"}"`

Is there a way to validate the validation allowing for that third attribute in the JSON return?

**Comment by dasdachs** [comment]
I just downgraded both packages. But I hope it gets resolved. Sadly I don't have the nodejs skills to make a decent pull request, other then to update `package.json`.

**Comment by ingusmat** [comment]
Thanks @dasdachs. I can confirm the solution now validates!

**Comment by dasdachs** [comment]
@ingusmat thanks! I finished it 2 days ago. Best of luck!
