### ISSUE TITLE
Upgrade for hapi v17?

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [hapijs/makemehapi#196]
I was wondering if this tutorial is going to be updated to v17 of hapi. As it has some major changes. I would like to help with this.

**Comment by rdela** [comment]
@ankitsinghaniyaz Agree. See also https://github.com/hapijs/hapijs.com/pull/524 we need to update all tutorials on the site for v17 and some of that work could overlap

**Comment by fiveisprime** [comment]
This is definitely on my list. Sorry for the delay, it's a crazy time of year for me.

**Comment by rdela** [comment]
Awesome thanks Matt. I mentioned in hapi hour Slack I am going to https://nodeschool.io/los-angeles/ December 2nd, 2017, 2pm - 5pm with the intent of working on this or updating hapijs.com tutorials, or both. Hoping @jarrettch is into the idea or someone else there will be!

**Comment by jarrettch** [comment]
Awesome @rdela looking forward to seeing you there! I've never used hapi or built a workshopper(yet) but I'd be down to help however I can. Sounds like fun!

**Comment by TrueMarcus** [comment]
Is there any progress on this?  I am currently using makemehapi to learn the framework and it is frustrating when everything seems to be deprecated.

**Comment by fiveisprime** [comment]
Yeah, #198 is open and in review. Looks like some additional changes were pushed recently so I'll test and hopefully deploy today.

**Comment by fiveisprime** [comment]
Publishing now, it will land in makemehapi@7.0.0

**Comment by devinivy** [comment]
Thank you and @lancelot316 so much for the effort on this– I know it was a serious amount of work.  I look forward to trying it out!
