### ISSUE TITLE
Running/verifying solutions errors out with ECONNREFUSED

### ISSUE THREAD

**Issue by joyrexus** [hapijs/makemehapi#98]
I'm having problems when trying to run or verify solutions:

```
⚡ makemehapi run exercises/routes/solution/solution.js 
✗ Error connecting to http://localhost:23478: ECONNREFUSED

Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

I have no problems running solutions with node.

Details follow.

```
/usr/local/lib/node_modules/makemehapi:master⚡ node -v
v0.10.23
/usr/local/lib/node_modules/makemehapi:master⚡ ps aux | grep node
joyrexus        34430   0.0  0.0  2423368    188 s001  R+   11:52PM   0:00.00 grep node
joyrexus        34419   0.0  1.4  3028248  28472 s001  S    11:52PM   0:00.74 /usr/local/Cellar/node/0.10.23/bin/node exercises/hello_hapi/solution/solution.js 29844
/usr/local/lib/node_modules/makemehapi:master⚡ node -v
v0.10.23
/usr/local/lib/node_modules/makemehapi:master⚡ makemehapi version
makemehapi@0.2.6
/usr/local/lib/node_modules/makemehapi:master⚡ kill -9 34419
/usr/local/lib/node_modules/makemehapi:master⚡ ps aux | grep node
joyrexus        34455   0.0  0.0  2423368    260 s001  R+   11:54PM   0:00.00 grep node
/usr/local/lib/node_modules/makemehapi:master⚡ makemehapi run exercises/hello_hapi/solution/solution.js 
✗ Error connecting to http://localhost:30885: ECONNREFUSED

Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
/usr/local/lib/node_modules/makemehapi:master⚡ ps aux | grep node
joyrexus        34467   0.0  0.0  2423368    304 s001  R+   11:54PM   0:00.00 grep node
joyrexus        34461   0.0  1.4  3029296  28548 s001  S    11:54PM   0:00.76 /usr/local/Cellar/node/0.10.23/bin/node exercises/hello_hapi/solution/solution.js 30885
```

Any suggestions would be greatly appreciated.

**Comment by joyrexus** [comment]
@lloydbenson asked:

> do you know if its just this one exercise or others?

 Well, I had manually tweaked the setTimeout on a number of solutions, but these tweaks were overwritten when I npm reinstalled makemehapi to test the new version.  

I can't recall which exercises required it and I was never able to diagnose the root cause.  If I knew the root cause, I'd fix and submit a PR.   Upping the timeout to 2 seconds seems less than ideal, since it only affects some systems.  (I was only having problems running the workshop on my MacBook Air.  I did not experience any issues when running the workshop on my Desktop using the same version of node and makemehapi.)

Sorry I'm not able to be of more help.

**Comment by lloydbenson** [comment]
Just that is very helpful.  I was trying to determine if it was more of an
overall problem or just an issue specific to the exercise.  Sounds more
systemic.  Thanks again for pointing this out.

**Comment by roelof1967** [comment]
I have the same problem : see https://github.com/hapijs/makemehapi/issues/109
but for me changing the timeout to 2000 does not work. 

~~~

exercise.addProcessor(function (mode, callback) {

    this.submissionStdout.pipe(process.stdout);

    // replace stdout with our own streams
    this.submissionStdout = through2();
    if (mode == 'verify') {
        this.solutionStdout = through2();
    }

    setTimeout(query.bind(this, mode), 2000);

    process.nextTick(function () {
        callback(null, true)
    });

~~~

Roelof

**Comment by lloydbenson** [comment]
This has been published so closing this up.

**Comment by srperetz** [comment]
I still have the same issue on both the routes and hello_hapi exercises, and I have makemehapi 1.0.3, with the timeout set to 2000 in both of those exercises.  If I run it over and over, it eventually passes.  Not sure if it's the timeout at all.  It seems to be more about the port, perhaps?
